
version: '3.7' 
services:     
    underworld:
        container_name: underworld3-dev
        image: underworldcode/carbonite:petsc_dev
        hostname: "uw-container"
        volumes:
            - $PWD:/workspace/
        working_dir: "/workspace"
        ports:
            - "8888:8888"
            - "9999:9999"
        command: "jupyter notebook --ip='0.0.0.0' --no-browser --allow-root"

