project:
  type: book
  output-dir: _build/book

book:
  title: "Underworld3 Quick Start Guide"
  author: "Louis Moresi"
  date: "15/06/2024"
  bread-crumbs: false
  chapters:
      - index.qmd
      - Introduction.qmd

  navbar:
    search: true
    logo: media/MansoursNightmare.png
    background: "white"
    foreground: "#C58812" # ANU honey colour

  sidebar:
    # logo: Images/COS-EarthSciences-800.jpg
    # logo: Images/ANU-logo.jpg
    background: "white"
    # foreground: "#C58812" # ANU honey colour


bibliography: UnderworldDocumentation.bib

format:
  html:
    theme: flatly # united / simplex
    linkcolor: "#C58812"

    code-links:
      - text: Open in Binder
        icon: rocket-takeoff
        href: https://mybinder.org/v2/gh/underworld/underworld3/HEAD?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd
    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/underworld/underworld3
  
  pdf:
    documentclass: scrreprt



