project:
  type: book
  output-dir: _build/book

book:
  title: "Underworld3 Quick Start Guide"
  author: "Louis Moresi"
  date: "15/06/2024"
  bread-crumbs: false
  chapters:
    - index.qmd
    - Notebooks/1-Meshes.ipynb
    - Notebooks/2-Variables.ipynb
    - Notebooks/3-Symbolic_Forms.ipynb
    - Notebooks/4-Solvers.ipynb
    - Notebooks/5-Solvers.ipynb
    - NextSteps.qmd

  navbar:
    search: true
    background: "white"
    foreground: "#883344" # Diablo Hell Fire / Blood Red

  sidebar:
    logo: media/MansoursNightmare.png
    background: "white"

# bibliography: UnderworldDocumentation.bib

format:
  html:
    theme: [united, "assets/theme.scss"] # united / simplex / flatly
    mainfont: "Jost"
    fontsize: 0.9em
    linestretch: 1.7
    linkcolor: "#883344"
    number-sections: false
    number-depth: 1

    code-links:
      - text: Open in Binder
        icon: rocket-takeoff
        href: https://mybinder.org/v2/gh/underworld/underworld3/development?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd

    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/underworld/underworld3

  # pdf:
  #   documentclass: scrreprt
