name: uw3
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mpmath<=1.3
  - mesalib
  - numpy
  - scipy
  - mpich-mpicc
  - mpich-mpicxx
  - cython=3.*
  - petsc>=3.21.0
  - petsc4py>=3.21.0
  - mpi4py
  - h5py
  - sympy
  - pytest
  - ipython 
  - pyvista[all]
  - quarto
  - pip
  - pip:  
    - gmsh
    - jupyterlab>=4.1
    - jupytext>=1.16.1
    - pygments>=2.17.0
    - trame-vtk
    - trame-vuetify
  
