name: uw3
channels:
  - conda-forge
dependencies:
  - python=3.10
  - petsc=3.21.5
  - petsc4py=3.21.5
  - cython=3.*
  - mpmath<=1.3
  - mesalib
  - numpy
  - scipy
  - mpich-mpicc
  - mpich-mpicxx
  - mpi4py
  - h5py
  - sympy
  - pytest
  - ipython
  - pyvista
  - pip
  - pip:
      - gmsh
      - gmsh-api
      - jupyterlab
      - jupytext
      - pygments
      - trame-vtk
      - trame-vuetify
