{% set name = "underworld3" %}
{% set version = "0.9b" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host: 
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - python
    - setuptools
    - cython
    - mpi4py
    - petsc4py >=3.20.0

  run:
    - {{ compiler('c') }}
    - cython
    - python
    - petsc
    - petsc4py >=3.20.0
    - mpi4py
    - h5py
    - pint
    - pytest
    - typing_extensions
    - sympy
    - python-xxhash
    - python-gmsh
    - ipython
    - typeguard
    - nest-asyncio
    - pyvista

about:
  home: "https://github.com/underworldcode/underworld3"
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: "Underworld3 Geodynamics code"
  dev_url: https://github.com/underworldcode/underworld3

extra:
  maintainers:
    - jgiordani
    - lmoresi
