name: API docs / pdoc3 

# We should trigger this from an upload event. Note that pdoc requires us to import the 
# built code, so this is a building test as well as documentation deployment

on:
  push:      
    branches:
      - main 
      - development

  pull_request:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./.github/workflows/envs/build_uw.yml
          cache-downloads: true

      # the following may be needed if conda-forge is out of date
      - name: Add compatible petsc4py
        shell: bash -l {0}
        run: |
          export PETSC_DIR="/home/runner/micromamba-root/envs/uw3"
          pip3 install petsc4py --upgrade

      - name: Build UW3
        shell: bash -l {0}
        run: |
          export PETSC_DIR="/home/runner/micromamba-root/envs/uw3"
          VERSION=`python3 setup.py --version`
          echo "UW - version " ${VERSION}

          python3 setup.py develop
          pip3 install -e .

      - name: Build docs with pdoc
        shell: bash -l {0}
        run: |
          pytest
