name: API docs / jupyterbook

# We should trigger this from an upload event 

on:
  push:   # We publish the beta docs as well
    branches: 
      - main 
      - development

  # workflow_run:
  #   workflows: ["Conda Deployment"]
  #   branches: [master]
  #   types: 
  #     - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Cache build environment
        uses: actions/cache@v3
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            /opt/homebrew
            ~/.cache/pip
          key: macos-underworld3-jbdocs

      - name: homebrew install dependencies
        run: |
          brew update
          brew install python@3.10
          brew install petsc 
          brew install gmsh
          brew install jupyter 
 
      - name: Build docs with jupyterbook
        shell: bash -l {0}
        run: |
          VERSION=`python setup.py --version`
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
          cd Jupyterbook
          ./build-book.sh 

      # Note deploy key needs the ----BEGIN ... KEY---- lines too

      ## Always deploy to version directory
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_PR_KEY }}
          destination_dir: ${{ env.VERSION }}
          publish_dir: jupyterbook/_build/html

 