name: Build and test UW3

# We should trigger this from an upload event. Note that pdoc requires us to import the 
# built code, so this is a building test as well as documentation deployment

on:
  push:      
    branches:
      - main 
      - development

  pull_request:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./.github/workflows/envs/build_uw_test.yml
          cache-downloads: true
          cache-env: true

      # the following may be needed if conda-forge is out of date
      # - name: Add compatible petsc4py
      #   shell: bash -l {0}
      #   run: |
      #    export PETSC_DIR="/home/runner/micromamba-root/envs/uw3_test"
      #    pip3 install petsc4py==3.18 --upgrade

      # gmsh is such a pig to install properly
      - name: Add gmsh package
        shell: bash -l {0}
        run: |
          pip install gmsh

      - name: Build UW3 
        shell: bash -l {0}
        run: |
          export PETSC_DIR="/home/runner/micromamba-root/envs/uw3_test"
          VERSION=`python3 setup.py --version`
          echo "UW - version " ${VERSION}

          python3 setup.py develop
          pip3 install -e .

      # Test - split into short, low memory tests 0???_*
      #        and longer, solver-based tests 1???_*

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest tests/test_00??*py
          pytest tests/test_0[1-9]??*py
          pytest tests/test_1000*py tests/test_1001*py
          pytest tests/test_1002*py
          pytest tests/test_1004*py
          pytest tests/test_1003*py tests/test_1003*py
